apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: some-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        somekey: somevalue
    spec:
      containers:
      - name: somename
        image: somename:latest
