apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: some-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        somekey: somevalue
    spec:
      containers:
      - name: golang-ping-pong
        image: sebastianharko/golang-ping-pong:1.0
        imagePullPolicy: Always
