apiVersion: apps/v1
kind: Deployment
metadata:
  name: some-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        key: value
    spec:
      containers:
      - name: somename
        image: somename:latest
